//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneraXML.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class COUNTRIES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COUNTRIES()
        {
            this.INSTALLATIONS = new HashSet<INSTALLATIONS>();
        }
    
        public decimal COU_ID { get; set; }
        public string COU_DESCRIPTION { get; set; }
        public string COU_CODE { get; set; }
        public string COU_TEL_PREFIX { get; set; }
        public Nullable<decimal> COU_CUR_ID { get; set; }
    
        public virtual CURRENCIES CURRENCIES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSTALLATIONS> INSTALLATIONS { get; set; }
    }
}
