//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneraXML.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURRENCIES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CURRENCIES()
        {
            this.COUNTRIES = new HashSet<COUNTRIES>();
            this.INSTALLATIONS = new HashSet<INSTALLATIONS>();
        }
    
        public decimal CUR_ID { get; set; }
        public string CUR_NAME { get; set; }
        public string CUR_ISO_CODE { get; set; }
        public string CUR_ISO_CODE_NUM { get; set; }
        public string CUR_SYMBOL { get; set; }
        public Nullable<double> CUR_FACT { get; set; }
        public string CUR_MASK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COUNTRIES> COUNTRIES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSTALLATIONS> INSTALLATIONS { get; set; }
    }
}
