//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneraXML.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUPS_TYPES_ASSIGNATIONS
    {
        public decimal GTA_ID { get; set; }
        public string GTA_DESCRIPTION { get; set; }
        public decimal GTA_GRP_ID { get; set; }
        public decimal GTA_GRPT_ID { get; set; }
        public System.DateTime GTA_INI_APPLY_DATE { get; set; }
        public System.DateTime GTA_END_APPLY_DATE { get; set; }
    
        public virtual GROUPS GROUPS { get; set; }
        public virtual GROUPS_TYPES GROUPS_TYPES { get; set; }
    }
}
