//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneraXML.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUPS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GROUPS()
        {
            this.GROUPS1 = new HashSet<GROUPS>();
            this.GROUPS_HIERARCHY = new HashSet<GROUPS_HIERARCHY>();
            this.GROUPS_HIERARCHY1 = new HashSet<GROUPS_HIERARCHY>();
            this.GROUPS_TYPES_ASSIGNATIONS = new HashSet<GROUPS_TYPES_ASSIGNATIONS>();
            this.PARKING_SPACES = new HashSet<PARKING_SPACES>();
            this.UNITS_GROUPS = new HashSet<UNITS_GROUPS>();
        }
    
        public decimal GRP_ID { get; set; }
        public string GRP_DESCRIPTION { get; set; }
        public decimal GRP_INS_ID { get; set; }
        public string GRP_QUERY_EXT_ID { get; set; }
        public string GRP_EXT1_ID { get; set; }
        public string GRP_EXT2_ID { get; set; }
        public string GRP_EXT3_ID { get; set; }
        public string GRP_HASH { get; set; }
        public int GRP_TREE_TYPE { get; set; }
        public Nullable<decimal> GRP_LOG_GRP_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GROUPS> GROUPS1 { get; set; }
        public virtual GROUPS GROUPS2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GROUPS_HIERARCHY> GROUPS_HIERARCHY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GROUPS_HIERARCHY> GROUPS_HIERARCHY1 { get; set; }
        public virtual INSTALLATIONS INSTALLATIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GROUPS_TYPES_ASSIGNATIONS> GROUPS_TYPES_ASSIGNATIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARKING_SPACES> PARKING_SPACES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UNITS_GROUPS> UNITS_GROUPS { get; set; }
    }
}
