//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneraXML.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTALLATIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INSTALLATIONS()
        {
            this.DAY_HOURS_INTERVALS = new HashSet<DAY_HOURS_INTERVALS>();
            this.DAY_TYPES = new HashSet<DAY_TYPES>();
            this.GROUPS = new HashSet<GROUPS>();
            this.GROUPS_TYPES = new HashSet<GROUPS_TYPES>();
            this.RATE_BEHAVIOR_SETS = new HashSet<RATE_BEHAVIOR_SETS>();
            this.RATE_TYPES = new HashSet<RATE_TYPES>();
            this.TARIFF_CONSTRAINTS_SETS = new HashSet<TARIFF_CONSTRAINTS_SETS>();
            this.TARIFFS = new HashSet<TARIFFS>();
            this.TICKET_TYPES = new HashSet<TICKET_TYPES>();
            this.UNITS = new HashSet<UNITS>();
        }
    
        public decimal INS_ID { get; set; }
        public string INS_DESCRIPTION { get; set; }
        public string INS_SHORTDESC { get; set; }
        public decimal INS_COU_ID { get; set; }
        public decimal INS_CUR_ID { get; set; }
        public string INS_TIMEZONE_ID { get; set; }
        public Nullable<decimal> INS_SECOND1_CUR_ID { get; set; }
        public Nullable<decimal> INS_SECOND2_CUR_ID { get; set; }
        public Nullable<int> INS_INFO_SCREEN_IMAGE_WIDTH { get; set; }
        public Nullable<int> INS_INFO_SCREEN_IMAGE_HEIGHT { get; set; }
        public Nullable<int> INS_INFO_SCREEN_IMAGE_OFFSET_X { get; set; }
        public Nullable<int> INS_INFO_SCREEN_IMAGE_OFFSET_Y { get; set; }
        public Nullable<int> INS_WAKEUP_SCREEN_IMAGE_WIDTH { get; set; }
        public Nullable<int> INS_WAKEUP_SCREEN_IMAGE_HEIGHT { get; set; }
        public Nullable<int> INS_WAKEUP_SCREEN_IMAGE_OFFSET_X { get; set; }
        public Nullable<int> INS_WAKEUP_SCREEN_IMAGE_OFFSET_Y { get; set; }
        public Nullable<int> INS_RECHARGE_MIN_ALLOWED { get; set; }
        public Nullable<int> INS_RECHARGE_MAX_ALLOWED { get; set; }
        public Nullable<int> INS_WALLET_MAX_BALANCE { get; set; }
        public string INS_RECHARGE_INCREMENTS { get; set; }
        public string INS_RECHARGE_DECREMENTS { get; set; }
    
        public virtual COUNTRIES COUNTRIES { get; set; }
        public virtual CURRENCIES CURRENCIES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAY_HOURS_INTERVALS> DAY_HOURS_INTERVALS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAY_TYPES> DAY_TYPES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GROUPS> GROUPS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GROUPS_TYPES> GROUPS_TYPES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RATE_BEHAVIOR_SETS> RATE_BEHAVIOR_SETS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RATE_TYPES> RATE_TYPES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TARIFF_CONSTRAINTS_SETS> TARIFF_CONSTRAINTS_SETS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TARIFFS> TARIFFS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TICKET_TYPES> TICKET_TYPES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UNITS> UNITS { get; set; }
    }
}
