//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneraXML.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BCTOTA2PAEntities : DbContext
    {
        public BCTOTA2PAEntities()
            : base("name=BCTOTA2PAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COUNTRIES> COUNTRIES { get; set; }
        public virtual DbSet<CURRENCIES> CURRENCIES { get; set; }
        public virtual DbSet<GROUPS> GROUPS { get; set; }
        public virtual DbSet<GROUPS_HIERARCHY> GROUPS_HIERARCHY { get; set; }
        public virtual DbSet<GROUPS_TYPES> GROUPS_TYPES { get; set; }
        public virtual DbSet<GROUPS_TYPES_ASSIGNATIONS> GROUPS_TYPES_ASSIGNATIONS { get; set; }
        public virtual DbSet<INSTALLATIONS> INSTALLATIONS { get; set; }
        public virtual DbSet<PARKING_SPACES> PARKING_SPACES { get; set; }
        public virtual DbSet<UNIT_ALARM_TYPES> UNIT_ALARM_TYPES { get; set; }
        public virtual DbSet<UNITS> UNITS { get; set; }
        public virtual DbSet<UNITS_GROUPS> UNITS_GROUPS { get; set; }
        public virtual DbSet<UNITS_LOGICAL_PARKING_SPACES> UNITS_LOGICAL_PARKING_SPACES { get; set; }
        public virtual DbSet<UNITS_PHYSICAL_PARKING_SPACES> UNITS_PHYSICAL_PARKING_SPACES { get; set; }
        public virtual DbSet<UNITS_SYNC_VERSIONS> UNITS_SYNC_VERSIONS { get; set; }
    }
}
