//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneraXML.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BCTOTA2PAEntitiesCompleto : DbContext
    {
        public BCTOTA2PAEntitiesCompleto()
            : base("name=BCTOTA2PAEntitiesCompleto")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COUNTRIES> COUNTRIES { get; set; }
        public virtual DbSet<CURRENCIES> CURRENCIES { get; set; }
        public virtual DbSet<DAY_EXCEPTIONS> DAY_EXCEPTIONS { get; set; }
        public virtual DbSet<DAY_HOURS_INTERVALS> DAY_HOURS_INTERVALS { get; set; }
        public virtual DbSet<DAY_TYPES> DAY_TYPES { get; set; }
        public virtual DbSet<GROUPS> GROUPS { get; set; }
        public virtual DbSet<GROUPS_HIERARCHY> GROUPS_HIERARCHY { get; set; }
        public virtual DbSet<GROUPS_TYPES> GROUPS_TYPES { get; set; }
        public virtual DbSet<GROUPS_TYPES_ASSIGNATIONS> GROUPS_TYPES_ASSIGNATIONS { get; set; }
        public virtual DbSet<INSTALLATIONS> INSTALLATIONS { get; set; }
        public virtual DbSet<LANGUAGES> LANGUAGES { get; set; }
        public virtual DbSet<PARKING_SPACES> PARKING_SPACES { get; set; }
        public virtual DbSet<RATE_BEHAVIOR_SETS> RATE_BEHAVIOR_SETS { get; set; }
        public virtual DbSet<RATE_BEHAVIOR_STEP> RATE_BEHAVIOR_STEP { get; set; }
        public virtual DbSet<RATE_STEPS> RATE_STEPS { get; set; }
        public virtual DbSet<RATE_TYPES> RATE_TYPES { get; set; }
        public virtual DbSet<TARIFF_CONSTRAINT_ENTRIES> TARIFF_CONSTRAINT_ENTRIES { get; set; }
        public virtual DbSet<TARIFF_CONSTRAINTS_SETS> TARIFF_CONSTRAINTS_SETS { get; set; }
        public virtual DbSet<TARIFFS> TARIFFS { get; set; }
        public virtual DbSet<TARIFFS_APPLICATION_RULES> TARIFFS_APPLICATION_RULES { get; set; }
        public virtual DbSet<TARIFFS_DEFINITION_RULES> TARIFFS_DEFINITION_RULES { get; set; }
        public virtual DbSet<TICKET_TYPES> TICKET_TYPES { get; set; }
        public virtual DbSet<TICKETS_TYPES_FEATURES> TICKETS_TYPES_FEATURES { get; set; }
        public virtual DbSet<UNIT_ALARM_TYPES> UNIT_ALARM_TYPES { get; set; }
        public virtual DbSet<UNIT_LITERAL_KEYS> UNIT_LITERAL_KEYS { get; set; }
        public virtual DbSet<UNIT_LITERAL_VERSIONS> UNIT_LITERAL_VERSIONS { get; set; }
        public virtual DbSet<UNIT_LITERALS> UNIT_LITERALS { get; set; }
        public virtual DbSet<UNIT_LITERALS_LANGUAGES> UNIT_LITERALS_LANGUAGES { get; set; }
        public virtual DbSet<UNIT_SETTING_PARAMETERS> UNIT_SETTING_PARAMETERS { get; set; }
        public virtual DbSet<UNIT_SETTING_SECTIONS> UNIT_SETTING_SECTIONS { get; set; }
        public virtual DbSet<UNIT_SETTING_VERSIONS> UNIT_SETTING_VERSIONS { get; set; }
        public virtual DbSet<UNIT_SETTINGS> UNIT_SETTINGS { get; set; }
        public virtual DbSet<UNIT_SETTINGS_DETAILS> UNIT_SETTINGS_DETAILS { get; set; }
        public virtual DbSet<UNITS> UNITS { get; set; }
        public virtual DbSet<UNITS_GROUPS> UNITS_GROUPS { get; set; }
        public virtual DbSet<UNITS_LITERALS_LANGUAGES_EXCEPTIONS> UNITS_LITERALS_LANGUAGES_EXCEPTIONS { get; set; }
        public virtual DbSet<UNITS_LOCATIONS> UNITS_LOCATIONS { get; set; }
        public virtual DbSet<UNITS_LOGICAL_PARKING_SPACES> UNITS_LOGICAL_PARKING_SPACES { get; set; }
        public virtual DbSet<UNITS_PHYSICAL_PARKING_SPACES> UNITS_PHYSICAL_PARKING_SPACES { get; set; }
        public virtual DbSet<UNITS_SETTINGS_DETAILS_EXCEPTIONS> UNITS_SETTINGS_DETAILS_EXCEPTIONS { get; set; }
        public virtual DbSet<UNITS_STATUS> UNITS_STATUS { get; set; }
        public virtual DbSet<UNITS_SYNC_VERSIONS> UNITS_SYNC_VERSIONS { get; set; }
    }
}
