//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneraXML.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARKING_SPACES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PARKING_SPACES()
        {
            this.UNITS_LOGICAL_PARKING_SPACES = new HashSet<UNITS_LOGICAL_PARKING_SPACES>();
            this.UNITS_PHYSICAL_PARKING_SPACES = new HashSet<UNITS_PHYSICAL_PARKING_SPACES>();
        }
    
        public decimal PSP_ID { get; set; }
        public string PSP_DESCRIPTION { get; set; }
        public string PSP_EXT_ID { get; set; }
        public string PSP_PHY_ID { get; set; }
        public int PSP_PHY_STATUS { get; set; }
        public System.DateTime PSP_PHY_STATUS_UTC_DATE { get; set; }
        public int PSP_LOG_STATUS { get; set; }
        public System.DateTime PSP_LOG_STATUS_UTC_DATE { get; set; }
        public int PSP_COMM_STATUS { get; set; }
        public Nullable<System.DateTime> PSP_COMM_UTC_DATE { get; set; }
        public Nullable<decimal> PSP_STSE_ID { get; set; }
        public Nullable<decimal> PSP_GRP_ID { get; set; }
        public Nullable<decimal> PSP_GPS_LATITUDE { get; set; }
        public Nullable<decimal> PSP_GPS_LONGITUDE { get; set; }
        public Nullable<decimal> PSP_OPE_ID { get; set; }
    
        public virtual GROUPS GROUPS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UNITS_LOGICAL_PARKING_SPACES> UNITS_LOGICAL_PARKING_SPACES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UNITS_PHYSICAL_PARKING_SPACES> UNITS_PHYSICAL_PARKING_SPACES { get; set; }
    }
}
