//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneraXML.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class RATE_BEHAVIOR_STEP
    {
        public decimal RBSS_ID { get; set; }
        public string RBSS_DESCRIPTION { get; set; }
        public decimal RBSS_RBS_ID { get; set; }
        public int RBSS_ORDER { get; set; }
        public Nullable<decimal> RBSS_RAT_ID { get; set; }
        public Nullable<decimal> RBSS_DAT_ID { get; set; }
        public Nullable<decimal> RBSS_DEX_ID { get; set; }
        public Nullable<System.DateTime> RBSS_DATE { get; set; }
        public Nullable<decimal> RBSS_DAH { get; set; }
        public string RBSS_INI_HOUR { get; set; }
        public string RBSS_END_HOUR { get; set; }
        public Nullable<int> RBSS_DAY_NUM_OF_APPLICATION { get; set; }
        public System.DateTime RBSS_INI_APPLY_DATE { get; set; }
        public System.DateTime RBSS_END_APPLY_DATE { get; set; }
        public int RBSS_ALLOW_JUMP_NEXT_BLOCK { get; set; }
        public Nullable<int> RBSS_CONDITIONAL_VALUE_FOR_NEXT_BLOCK { get; set; }
        public int RBSS_RESET_TIME_WHEN_JUMP_NEXT_BLOCK { get; set; }
        public int RBSS_RESET_AMOUNT_WHEN_JUMP_NEXT_BLOCK { get; set; }
        public int RBSS_ROUND_FINAL_PARKING_TO_STEP_END { get; set; }
    
        public virtual DAY_EXCEPTIONS DAY_EXCEPTIONS { get; set; }
        public virtual DAY_HOURS_INTERVALS DAY_HOURS_INTERVALS { get; set; }
        public virtual DAY_TYPES DAY_TYPES { get; set; }
        public virtual RATE_BEHAVIOR_SETS RATE_BEHAVIOR_SETS { get; set; }
        public virtual RATE_TYPES RATE_TYPES { get; set; }
    }
}
