//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneraXML.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class RATE_BEHAVIOR_SETS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RATE_BEHAVIOR_SETS()
        {
            this.RATE_BEHAVIOR_STEP = new HashSet<RATE_BEHAVIOR_STEP>();
            this.TARIFFS_DEFINITION_RULES = new HashSet<TARIFFS_DEFINITION_RULES>();
        }
    
        public decimal RBS_ID { get; set; }
        public string RBS_DESCRIPTION { get; set; }
        public decimal RBS_INS_ID { get; set; }
    
        public virtual INSTALLATIONS INSTALLATIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RATE_BEHAVIOR_STEP> RATE_BEHAVIOR_STEP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TARIFFS_DEFINITION_RULES> TARIFFS_DEFINITION_RULES { get; set; }
    }
}
