//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneraXML.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class RATE_STEPS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RATE_STEPS()
        {
            this.RATE_TYPES1 = new HashSet<RATE_TYPES>();
        }
    
        public decimal RAS_ID { get; set; }
        public string RAS_DESCRIPTION { get; set; }
        public decimal RAS_RAT_ID { get; set; }
        public int RAS_ORDER { get; set; }
        public decimal RAS_AMOUNT { get; set; }
        public decimal RAS_NUM_MINUTES { get; set; }
        public int RAS_INTERVAL_VALUE_TYPE { get; set; }
        public int RAS_INTERMEDIATE_VALUES_VALID { get; set; }
        public string RAS_HASH { get; set; }
    
        public virtual RATE_TYPES RATE_TYPES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RATE_TYPES> RATE_TYPES1 { get; set; }
    }
}
