//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneraXML.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TARIFFS_APPLICATION_RULES
    {
        public decimal TAPR_ID { get; set; }
        public string TAPR_DESCRIPTON { get; set; }
        public decimal TAPR_TAR_ID { get; set; }
        public Nullable<decimal> TAPR_UNI_ID { get; set; }
        public Nullable<decimal> TAPR_GRP_ID { get; set; }
        public Nullable<decimal> TAPR_GRPT_ID { get; set; }
        public System.DateTime TAPR_INI_APPLY_DATE { get; set; }
        public System.DateTime TAPR_END_APPLY_DATE { get; set; }
        public Nullable<decimal> TAPR_DAT_ID { get; set; }
        public Nullable<decimal> TAPR_DAH_ID { get; set; }
        public string TARP_IN_DAY_INI_HOUR { get; set; }
        public string TARP_IN_DAY_END_HOUR { get; set; }
        public Nullable<System.DateTime> TAPR_IN_YEAR_INI_DATE { get; set; }
        public Nullable<System.DateTime> TAPR_IN_YEAR_END_DATE { get; set; }
        public Nullable<int> TAPR_SHOW_ORDER { get; set; }
        public int TAPR_ALLOW_USER_SELECT { get; set; }
        public int TAPR_INSERT_PLATE { get; set; }
        public int TAPR_SPACE_MANAGMENT_TYPE { get; set; }
        public Nullable<decimal> TAPR_TCS_ID { get; set; }
        public int TAPR_PLATE_TARIFF_ASSIGN_TYPE { get; set; }
        public Nullable<int> TAPR_TIMEAMOUNT_SEL_TYPE { get; set; }
        public Nullable<int> TAPR_PAY_MODE { get; set; }
        public Nullable<int> TAPR_INC1 { get; set; }
        public Nullable<int> TAPR_INC2 { get; set; }
        public Nullable<int> TAPR_INC3 { get; set; }
        public Nullable<int> TAPR_INC4 { get; set; }
        public Nullable<int> TAPR_INC5 { get; set; }
        public Nullable<int> TAPR_DEC1 { get; set; }
        public Nullable<int> TAPR_DEC2 { get; set; }
        public Nullable<int> TAPR_DEC3 { get; set; }
        public Nullable<int> TAPR_DEC4 { get; set; }
        public Nullable<int> TAPR_DEC5 { get; set; }
        public Nullable<int> TAPR_ACCESS_CARD_TYPE { get; set; }
        public Nullable<int> TAPR_ACCESS_CARD_NUM { get; set; }
        public Nullable<int> TAPR_CONNECTION_REQUIRED { get; set; }
        public int TAPR_ALLOW_REMOTE_EXTENSION { get; set; }
        public int TAPR_TARIFF_ENGINE { get; set; }
    
        public virtual DAY_HOURS_INTERVALS DAY_HOURS_INTERVALS { get; set; }
        public virtual DAY_TYPES DAY_TYPES { get; set; }
        public virtual GROUPS GROUPS { get; set; }
        public virtual GROUPS_TYPES GROUPS_TYPES { get; set; }
        public virtual TARIFF_CONSTRAINTS_SETS TARIFF_CONSTRAINTS_SETS { get; set; }
        public virtual TARIFFS TARIFFS { get; set; }
        public virtual UNITS UNITS { get; set; }
    }
}
