//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneraXML.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TARIFF_CONSTRAINT_ENTRIES
    {
        public decimal TCE_ID { get; set; }
        public string TCE_DESCRIPTION { get; set; }
        public decimal TCE_TCS_ID { get; set; }
        public Nullable<decimal> TCE_GRP_ID { get; set; }
        public Nullable<decimal> TCE_GRPT_ID { get; set; }
        public int TCE_MAX_PARKING_TIME { get; set; }
        public int TCE_MIN_PARKING_AMOUNT { get; set; }
        public int TCE_MAX_PARKING_AMOUNT { get; set; }
        public int TCE_PARALEL_PARKING_ALLOWED { get; set; }
        public int TCE_QUERY_HISTORY_OPERATIONS { get; set; }
        public int TCE_COURTESY_TIME_IN_EXTENSION { get; set; }
        public int TCE_COURTESY_TIME_MUST_BE_PAID { get; set; }
        public int TCE_ALLOW_EXTENSIONS { get; set; }
        public int TCE_ALLOW_REFUNDS { get; set; }
        public int TCE_EXTENSION_MAX_SLIDING_WINDOW { get; set; }
        public int TCE_MIN_AMOUNT_TO_BE_CHARGED_IN_EXTENSIONS { get; set; }
        public int TCE_MIN_AMOUNT_TO_BE_CHARGED_IN_REFUNDS { get; set; }
        public int TCE_MIN_REENTRY_TIME { get; set; }
        public int TCE_NUM_TARIFF_MINUTES_FOR_NOT_APP_REENTRY { get; set; }
        public int TCE_INTRA_GROUP_PARK { get; set; }
        public int TCE_INTRA_GROUP_PARK_COURTESY_TIME { get; set; }
    
        public virtual GROUPS GROUPS { get; set; }
        public virtual GROUPS_TYPES GROUPS_TYPES { get; set; }
        public virtual TARIFF_CONSTRAINTS_SETS TARIFF_CONSTRAINTS_SETS { get; set; }
    }
}
