//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneraXML.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKETS_TYPES_FEATURES
    {
        public decimal TITF_ID { get; set; }
        public decimal TITF_TITY_ID { get; set; }
        public System.DateTime TITF_INIDATE { get; set; }
        public System.DateTime TITF_ENDDATE { get; set; }
        public int TITF_PAYABLE { get; set; }
        public int TITF_AMOUNT { get; set; }
        public Nullable<int> TITF_COUNCIL_AMOUNT { get; set; }
        public int TITF_PERIOD_TYPE { get; set; }
        public Nullable<int> TITF_INI_NUM_MINUTES { get; set; }
        public Nullable<int> TITF_END_NUM_MINUTES { get; set; }
        public Nullable<decimal> TITF_DAT_ID { get; set; }
    
        public virtual DAY_TYPES DAY_TYPES { get; set; }
        public virtual TICKET_TYPES TICKET_TYPES { get; set; }
    }
}
