//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneraXML.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIT_ALARM_TYPES
    {
        public decimal UAT_ID { get; set; }
        public string UAT_NAME { get; set; }
        public string UAT_DESCRIPTION { get; set; }
        public Nullable<long> UAT_HW_MASK { get; set; }
        public int UAT_LEVEL { get; set; }
        public string UAT_COLOR { get; set; }
        public Nullable<int> UAT_SALES_MODE { get; set; }
    }
}
