//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneraXML.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIT_LITERAL_KEYS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UNIT_LITERAL_KEYS()
        {
            this.UNIT_LITERALS_LANGUAGES = new HashSet<UNIT_LITERALS_LANGUAGES>();
            this.UNITS_LITERALS_LANGUAGES_EXCEPTIONS = new HashSet<UNITS_LITERALS_LANGUAGES_EXCEPTIONS>();
        }
    
        public decimal ULK_ID { get; set; }
        public Nullable<decimal> ULK_ULV_ID { get; set; }
        public string ULK_KEY { get; set; }
    
        public virtual UNIT_LITERAL_VERSIONS UNIT_LITERAL_VERSIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UNIT_LITERALS_LANGUAGES> UNIT_LITERALS_LANGUAGES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UNITS_LITERALS_LANGUAGES_EXCEPTIONS> UNITS_LITERALS_LANGUAGES_EXCEPTIONS { get; set; }
    }
}
