//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneraXML.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNITS_GROUPS
    {
        public decimal UNGR_ID { get; set; }
        public string UNGR_DESCRIPTION { get; set; }
        public decimal UNGR_UNI_ID { get; set; }
        public decimal UNGR_GRP_ID { get; set; }
        public System.DateTime UNGR_INI_APPLY_DATE { get; set; }
        public System.DateTime UNGR_END_APPLY_DATE { get; set; }
    
        public virtual GROUPS GROUPS { get; set; }
        public virtual UNITS UNITS { get; set; }
    }
}
