//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneraXML.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNITS_LOCATIONS
    {
        public decimal UNLO_ID { get; set; }
        public string UNLO_DESCRIPTION { get; set; }
        public decimal UNLO_UNI_ID { get; set; }
        public decimal UNLO_GPS_LATITUDE { get; set; }
        public decimal UNLO_GPS_LONGITUDE { get; set; }
        public System.DateTime UNLO_INI_APPLY_DATE { get; set; }
        public System.DateTime UNLO_END_APPLY_DATE { get; set; }
    
        public virtual UNITS UNITS { get; set; }
    }
}
