//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneraXML.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNITS_LITERALS_LANGUAGES_EXCEPTIONS
    {
        public decimal UNIL_ID { get; set; }
        public decimal UNIL_UNI_ID { get; set; }
        public decimal UNIL_ULK_ID { get; set; }
        public decimal UNIL_LAN_ID { get; set; }
        public string UNIL_LITERAL { get; set; }
    
        public virtual LANGUAGES LANGUAGES { get; set; }
        public virtual UNIT_LITERAL_KEYS UNIT_LITERAL_KEYS { get; set; }
        public virtual UNITS UNITS { get; set; }
    }
}
