//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneraXML.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIT_SETTINGS_DETAILS
    {
        public decimal USTD_ID { get; set; }
        public decimal USTD_UST_ID { get; set; }
        public decimal USTD_USP_ID { get; set; }
        public string USTD_PARAM_VALUE { get; set; }
    
        public virtual UNIT_SETTING_PARAMETERS UNIT_SETTING_PARAMETERS { get; set; }
        public virtual UNIT_SETTINGS UNIT_SETTINGS { get; set; }
    }
}
