//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneraXML.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNITS_SYNC_VERSIONS
    {
        public decimal USYV_ID { get; set; }
        public decimal USYV_UNI_ID { get; set; }
        public string USYV_TABLE_NAME { get; set; }
        public decimal USYV_CURR_VERSION { get; set; }
    
        public virtual UNITS UNITS { get; set; }
    }
}
