//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneraXML.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIT_SETTING_PARAMETERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UNIT_SETTING_PARAMETERS()
        {
            this.UNIT_SETTINGS_DETAILS = new HashSet<UNIT_SETTINGS_DETAILS>();
            this.UNITS_SETTINGS_DETAILS_EXCEPTIONS = new HashSet<UNITS_SETTINGS_DETAILS_EXCEPTIONS>();
        }
    
        public decimal USP_ID { get; set; }
        public decimal USP_USV_ID { get; set; }
        public decimal USP_USS_ID { get; set; }
        public string USP_NAME { get; set; }
    
        public virtual UNIT_SETTING_SECTIONS UNIT_SETTING_SECTIONS { get; set; }
        public virtual UNIT_SETTING_VERSIONS UNIT_SETTING_VERSIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UNIT_SETTINGS_DETAILS> UNIT_SETTINGS_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UNITS_SETTINGS_DETAILS_EXCEPTIONS> UNITS_SETTINGS_DETAILS_EXCEPTIONS { get; set; }
    }
}
